### PR TITLE
opae-sim: merge ase/README into top-level readme

### PR DESCRIPTION
**Pull request by r-rojo**
* Move/update build istructions from ase/README.md
* Remove ase/README.md

Signed-off-by: Rodrigo Rojo <rodrigo.rojo@intel.com>

### CODE REVIEW

**Review by michael-adler — COMMENTED** [review]
I suspect there's some knowledge you have about the CMAKE_PREFIX_PATH and opae_DIR that most of our users won't understand unless you make it explicit.

Does CMAKE_PREFIX_PATH set the installation target but doesn't help in finding the OPAE installation?

Does opae_DIR find OPAE but not affect installation?

If yes, perhaps say that most users should do the first, then describe the other two and when someone might use them.

**Comment by r-rojo** [comment]
I thought I had made that distinction by stating "... and will also control where ASE libraries are installed."
If you think it needs to be more explicit then I can do so.

**Comment by michael-adler** [comment]
It's too subtle. I only knew what you meant because of our previous conversation.

**Review by michael-adler — APPROVED** [review]
Thanks

**Pull request merged**
