### PR TITLE
ase/buffer: fix allocation on systems with default 1GB hugepage

### PR DESCRIPTION
**Pull request by ddcc**
When a MAP_HUGETLB mapping is requested without specifying a desired huge page size, it will use the system's default huge page size. This means that on a system with default 1GB huge pages, a request for 2MB can be rounded up to 1GB. Explicitly specify the size in all cases to prevent this from occurring.

### CODE REVIEW

**Comment by ddcc** [comment]
This is the ASE pull request version of https://github.com/OPAE/opae-libs/pull/19.

**Comment by michael-adler** [comment]
Sorry this took so long.

The code may work on new systems, but fails on older ones. It needs explicit definition of MAP_2M_HUGEPAGE and MAP_1G_HUGEPAGE, similar to [common_int.h](https://github.com/OPAE/opae-sdk/blob/bde838b8d903e9339d876f8c8a127e4bbbeeefd1/opae-libs/plugins/xfpga/common_int.h#L72).

**Comment by ddcc** [comment]
Those should be defined on lines 59 and 60 of the same file.

**Comment by michael-adler** [comment]
Sorry, you're right. I was lazily cutting and pasting instead of connecting to your repository. Will try again.

**Pull request merged**
